#!/bin/bash

# Check the Java version
JV=$(java -version 2>&1 | head -n 1 | grep -oP '"\K[^"]+')

# Function to install and use SDKMAN with a specific Java version
install_and_use_java() {
    echo "Installing SDKMAN..."
    curl -s "https://get.sdkman.io" | bash
    source ~/.sdkman/bin/sdkman-init.sh
    sdk version
    sdk install java "$1"
    sdk use java "$1"
}

# Check if the current Java version is not 17 or 21
if [[ "$JV" != "17"* && "$JV" != "21"* ]]; then
    case "$1" in
    install)
        install_and_use_java "21.0.2-open"
        ;;
    use)
        echo "must source ~/.sdkman/bin/sdkman-init.sh"
        exit 1
        ;;
    esac
elif [[ "$JV" == "21"* ]]; then
    install_and_use_java "17.0.8-open"
fi